### ISSUE TITLE
Facter 3.0.1 Compatability?

### ISSUE THREAD

**Issue by johnzimm** [gentoo/puppet-portage#136]
Currently porting my puppet code over to puppetserver 2.1 (puppet 4.2) using the "Puppet Collection 1" repos on CentOS 6.

Facter 3.0.1 is what is installed from this collection.  Getting this error when during a puppet run with the "puppet-agent" package.

```
Info: Loading facts
Error: Facter: error while resolving custom facts in /opt/puppetlabs/puppet/cache/lib/facter/portage.rb: cannot load such file -- facter/util/resolution
```

**Comment by vikraman** [comment]
Fixed in #137
