### ISSUE TITLE
Add possibilty to set keyword versions for module maintained packages

### ISSUE THREAD

**Issue by samuraiii** [gentoo/puppet-portage#145]
It is nice that you can set keywords for portage etc..
It would be also nice to set versions for keywords

**Comment by samuraiii** [comment]
https://github.com/gentoo/puppet-portage/pull/146
https://github.com/gentoo/puppet-portage/pull/147
https://github.com/gentoo/puppet-portage/pull/148

Sorry for split PRs
This should fix it

**Comment by robbat2** [comment]
Implemented
